feat: support NOBBIC_START_AUTOBUILD variable with "yes" or "no" values
Defaults to "yes", but OpenRC and SystemD service templates
set it to "no".

When not "yes", nobbic will not try to build pod from the `start` action.
It will simply exit with error, if pod does not exists.

This fixes problem reported by @nhlpl: when service was not removed,
after pod was removed, reboot caused building another pod with the same
name (but almost empty, and failing, because NodeBB needs database).
That could prevent another service from running correctly because of
using the same default port number(s).

diff --git a/nobbic b/nobbic
--- a/nobbic
+++ b/nobbic
@@ -215,7 +215,15 @@ function startPod () {
 	fi
 
 	local existed=$(podman pod exists "$APP_NAME" && echo "exists");
-	test "$existed" || buildPod "$APP_NAME" || return $?
+	if [ -z "$existed" ] ; then
+		if [ "${NOBBIC_START_AUTOBUILD:-yes}" = "yes" ] ; then
+			buildPod "$APP_NAME" || return $?
+		else
+			echo "ERROR: no pod exists for ${APP_NAME}" >&2
+			echo "       try to build it first" >&2
+			return 1
+		fi
+	fi
 
 	if test "$existed" ; then
 		echo "Restarting '$APP_NAME' pod..."
